steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.5"
          channel: "stable"

      - name: Flutter pub get
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      # Removed the "Run tests" step since no tests exist

      - name: Build APK
        run: flutter build apk --release

